name: Django-app workflow

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: | 
        # обновление pip
        python -m pip install --upgrade pip 
        # установка flake8 и его плагинов
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
        # установка зависимостей
        pip install -r requirements.txt 

    - name: Test with flake8 and django tests
      run: |
        # запуск проверки проекта по flake8
        python -m flake8
        # перейти в папку, содержащую manage.py — 
        #<корневая_папка_infra_actions>/<папка_проекта>/manage.py
        cd infra_project/
        # запустить написанные разработчиком тесты
        python manage.py test

  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Check out the repo
        # Проверка доступности репозитория Docker Hub для workflow
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        # Вызов сборщика контейнеров docker
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        # Запуск скрипта авторизации на Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        # Пуш образа в Docker Hub 
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: hazardbdv/infra_actions:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
    - name: executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: 51.250.6.95
        username: bitkov-practicum
        key: b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABCaatT8r4
qxzWS5MUTsyVQ+AAAAEAAAAAEAAAGXAAAAB3NzaC1yc2EAAAADAQABAAABgQCpI9qHKOKc
EV/CmTTCgYzRE4OsuLB5ms6FM+uI3YrmyCMLi1bb4DweeS14pKFPZjxUTIlyoRhVTEosp7
cLFMddDSYfzbKd0pVQZYM3uSU1HiNPVQ1Fm/Cb7S73XQaayyh2+f4kKY8tGYAjfqHE1mmC
9t79RP9+bloibGaVo1vxWcQC13dMLSCglFtAO+OGDlfQXELoDdgePNI2ak12eA+kI5Gcbn
X9HvVuDP2LVx/nDkuqsbX4cvWyhwgfFRggAcPGVjgpJlxOaZPiHFBqwX5RUQEAjWjrVPJX
GOoQIZiTT0Zi99p/Agb4pfciRqgqqiW8NoqzqT/APHLW3p2B5Pq8Nf0ufh7708a86Ygek0
qAx4zZRSXO3p4SwzC0BAS4bML6fsBoY5kdYys9r19uPSbIfcSBAwZMgqxG4D4FeMwTVe1h
3R842zmHwKTEQBADWTzQYh6Fttr6wybV/0FaiULm/dxBs1P+XJhkPsmZTUVQ1oakMVnQFD
43u2Yn3tdYtbEAAAWQoH+zRzpw499Tn6muSQvKrhIDJUjt7xj/E2CpPxl9WD5tDOTDFVfm
4FmFdta38jCTDxTpl/QuOe48R8Hl7H4e7heDsKiFi2z1oPdkHLN0xCK4iXOZ9wcBaG91CC
u8wuiI4hOF9kWs55i4DVEvpr8FGsLTvIJjqT9dM/9FCmmWcqTg62LtNdrXWyFitAVhYQE/
HMyaVI+NgnwsAaP5FGg3CerOx4h5K3Q8eGe5fve3s37OY18qeWmw/xXzC2CYSXtD8R8A23
pYh0BQpqaRK3hAn5om8jA/Es9+njx5mBu2F9ltIJDNPeg+YP53EY0DdNKUG5bHJfArm9rr
z6YZU/9HKq4mIwAiUZt6tQDSlvOIiWcfNP4E9qxokLIUEZ3/GDCbeF3ntpEcYbFBVOmSkq
ExUq0bP2SoDjGgV2njWrdT6rZ7KWnIjQVetw+V2OIQruT5PKDcSppQ6EhK/kEtZkiz7g4c
r069BS17NKFNa5nTCq77NKzhek9yLVzNbLx17rwZ5B2A1a8Gb1nhJHQRfzaYgu6ff+tEnA
FOb4aqvQ9EFzX891A7DFhjiM8V532NAIXShSNwFowQGB+LcxraGoI72MMywmo2PcaymO+e
Ee99050LKGiJFXwR1YbPxila0Y8pasgUX3JBi1uUdKn8SzsllJDfYnuaArv8AXi/Dw02KQ
IPQbQzmfzq6FNfFr7h6Vl2jSMKV5hFZv7a0Mmg6j4CyZw02uUjoKkkSGOvO3cebmgWIMSE
1tYhJ17F/BFAD9yrhHnAnr4tnoR5s04DYkkOi/t8OHQm1U8vDNntV3tN7GnyncU8K735eJ
9FaYKwDJUgkBlRCVXHzG3DBAlwyf5F7yHi2ZfSGbQEKBqExE9KvvDA+kaZD9aPHfMQ6w3R
Uxhsyy8iLArpBAE+mdeXsHPEzBGQShQadDzdOJvdCVfOWprd6j7FUIunlpKPTbFiFiI6hw
y0qJ99VmmQpQHbe+4aTBPq/IbB8KSneeP3/UOlMa/6+G2td+HJFc8/X8+HKu00hLqk1DsB
PPNoJ+C/+WtxzjVoe51OVegR4H7AIHTQVyIlg1FISHEYvjP3NuaNjt3p4VbtXlhcGd4jac
RkFBukbFmbkbsQD/Xn+GjDneP0kHxaYqH2wlxCuKqP4zjnqW3J8opBKPfl2c2b4ZdopNaq
Td6T1OjGOssU0lk4hUfRShvFX+MVHJ0dLgnIoa4ZeQr2THPgZC8f4OFiXD+o7q8Bb5znls
Yt+HVR+Mc6nPuRM8TK8SLWRJE3fTKT3TX+hNoTq/jOmYqd/NhtIw4b8zYmNrd4QjFifPpA
J72iOgZNVG5K8RCWT3q7bhDCL/UcuJjO6MO+JQCFAA8PvP8ZrOr7P0XXtBX/XI7+AzMtto
A3AGySu7gyMD1iGNnVEeo/JMWZeM5zY2DzKaY9eBqygb7hD8qd3KVS/CvUbN47sWEKAC0i
Q5wNwimYnkWldu7FfydmmbnAoB5/VcBtyeEqw+Om7el3v43tbrtVbVQNGWMY1Obr5vAhpB
f/IcdPW0W9YTD6LcEWjCi1c1g8YF3L8cLjx4XZheb+UisG+YpqTFnSBQIFkEeQG6t/cDBu
gLDzUiJVPh1KwaZflhagNZ2N2/O7J+f7v5K4xr44vIUjTmx9sCKgq7kYnpGyaQX2nXtS4D
ua+6hZmdN/POHXhYGwmU6WKLkq/W8sV7Xk3afYQnY4IrkN/6UGKQt0mYBMkNSDPTD1OayU
9ha6q1Qoc87EnzZB6Wr1KPJYfrqEUnhFtUauUS649P3FbCTZ7YUQ51ve035l4ILP0sRx+Y
ER44l/pU/+jK/FMZQeTu5Q4CCg9qxFD9lLwizNcGgXGtlgY8fJ2CDEe3BPMfBlAVYqMUZq
3BrYKiX+mdJ+yE2sSfv9SzoDH6Q=
        passphrase: 87878847
        #host: ${{ secrets.HOST }}
        #username: ${{ secrets.USER }}
        #key: ${{ secrets.SSH_KEY }}
        #passphrase: ${{ secrets.PASSPHRASE }} # Если ваш ssh-ключ защищён фразой-паролем
        script: |
          # Выполняет pull образа с DockerHub
          sudo docker pull hazardbdv/infra_actions
          #остановка всех контейнеров
          sudo docker stop $(sudo docker ps -a -q)
          sudo docker run --rm -d -p 5000:5000 hazardbdv/infra_actions
