name: Django-app workflow

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: | 
        # обновление pip
        python -m pip install --upgrade pip 
        # установка flake8 и его плагинов
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
        # установка зависимостей
        pip install -r requirements.txt 

    - name: Test with flake8 and django tests
      run: |
        # запуск проверки проекта по flake8
        python -m flake8
        # перейти в папку, содержащую manage.py — 
        #<корневая_папка_infra_actions>/<папка_проекта>/manage.py
        cd infra_project/
        # запустить написанные разработчиком тесты
        python manage.py test

  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Check out the repo
        # Проверка доступности репозитория Docker Hub для workflow
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        # Вызов сборщика контейнеров docker
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        # Запуск скрипта авторизации на Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        # Пуш образа в Docker Hub 
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: hazardbdv/infra_actions:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
    - name: executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: 51.250.6.95
        username: bitkov-practicum
        key: b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1
jdHIAAAAGYmNyeXB0AAAAGAAAABCaatT8r4qxzWS5MUTsyVQ
+AAAAEAAAAAEAAA
GXAAAAB3NzaC1yc2EAAAADAQABAAABgQCpI9qHKOKcEV/CmTTCgYzRE
4OsuLB5ms6FM+uI3YrmyCMLi1bb4DweeS14pKFPZjxUTIlyoRhVTEos
p7cLFMddDSYfzbKd0pVQZYM3uSU1HiNPVQ1Fm/Cb7S73XQaayyh2+f4
kKY8tGYAjfqHE1mmC9t79RP9+bloibGaVo1vxWcQC13dMLSCglFtAO+
OGDlfQXELoDdgePNI2ak12eA+kI5GcbnX9HvVuDP2LVx/nDkuqsbX4c
vWyhwgfFRggAcPGVjgpJlxOaZPiHFBqwX5RUQEAjWjrVPJXGOoQIZiT
T0Zi99p/Agb4pfciRqgqqiW8NoqzqT/APHLW3p2B5Pq8Nf0ufh7708
a86Ygek0qAx4zZRSXO3p4SwzC0BAS4bML6fsBoY5kdYys9r19uPSbI
fcSBAwZMgqxG4D4FeMwTVe1h3R842zmHwKTEQBADWTzQYh6Fttr6wy
bV/0FaiULm/dxBs1P+XJhkPsmZTUVQ1oakMVnQFD43u2Yn3tdYtbEA
AAWQoH+zRzpw499Tn6muSQvKrhIDJUjt7xj/E2CpPxl9WD5tDOTDF
Vfm4FmFdta38jCTDxTpl/QuOe48R8Hl7H4e7heDsKiFi2z1oPdkHL
N0xCK4iXOZ9wcBaG91CCu8wuiI4hOF9kWs55i4DVEvpr8FGsLTvIJ
jqT9dM/9FCmmWcqTg62LtNdrXWyFitAVhYQE/HMyaVI+NgnwsAaP5
FGg3CerOx4h5K3Q8eGe5fve3s37OY18qeWmw/xXzC2CYSXtD8R8A2
3pYh0BQpqaRK3hAn5om8jA/Es9+njx5mBu2F9ltIJDNPeg+YP53EY
0DdNKUG5bHJfArm9rrz6YZU/9HKq4mIwAiUZt6tQDSlvOIiWcfNP4
E9qxokLIUEZ3/GDCbeF3ntpEcYbFBVOmSkqExUq0bP2SoDjGgV2nj
WrdT6rZ7KWnIjQVetw+V2OIQruT5PKDcSppQ6EhK/kEtZkiz7g4cr
069BS17NKFNa5nTCq77NKzhek9yLVzNbLx17rwZ5B2A1a8Gb1nhJH
QRfzaYgu6ff+tEnAFOb4aqvQ9EFzX891A7DFhjiM8V532NAIXShSN
wFowQGB+LcxraGoI72MMywmo2PcaymO+eEe99050LKGiJFXwR1YbP
xila0Y8pasgUX3JBi1uUdKn8SzsllJDfYnuaArv8AXi/Dw02KQIPQ
bQzmfzq6FNfFr7h6Vl2jSMKV5hFZv7a0Mmg6j4CyZw02uUjoKkkSG
OvO3cebmgWIMSE1tYhJ17F/BFAD9yrhHnAnr4tnoR5s04DYkkOi/t
8OHQm1U8vDNntV3tN7GnyncU8K735eJ9FaYKwDJUgkBlRCVXHzG3D
BAlwyf5F7yHi2ZfSGbQEKBqExE9KvvDA+kaZD9aPHfMQ6w3RUxhsy
y8iLArpBAE+mdeXsHPEzBGQShQadDzdOJvdCVfOWprd6j7FUIunlp
KPTbFiFiI6hwy0qJ99VmmQpQHbe+4aTBPq/IbB8KSneeP3/UOlMa/
6+G2td+HJFc8/X8+HKu00hLqk1DsBPPNoJ+C/+WtxzjVoe51OVegR
4H7AIHTQVyIlg1FISHEYvjP3NuaNjt3p4VbtXlhcGd4jacRkFBukb
FmbkbsQD/Xn+GjDneP0kHxaYqH2wlxCuKqP4zjnqW3J8opBKPfl2c
2b4ZdopNaqTd6T1OjGOssU0lk4hUfRShvFX+MVHJ0dLgnIoa4ZeQr
2THPgZC8f4OFiXD+o7q8Bb5znlsYt+HVR+Mc6nPuRM8TK8SLWRJE3
fTKT3TX+hNoTq/jOmYqd/NhtIw4b8zYmNrd4QjFifPpAJ72iOgZNV
G5K8RCWT3q7bhDCL/UcuJjO6MO+JQCFAA8PvP8ZrOr7P0XXtBX/XI
7+AzMttoA3AGySu7gyMD1iGNnVEeo/JMWZeM5zY2DzKaY9eBqygb7
hD8qd3KVS/CvUbN47sWEKAC0iQ5wNwimYnkWldu7FfydmmbnAoB5/
VcBtyeEqw+Om7el3v43tbrtVbVQNGWMY1Obr5vAhpBf/IcdPW0W9Y
TD6LcEWjCi1c1g8YF3L8cLjx4XZheb+UisG+YpqTFnSBQIFkEeQG6
t/cDBugLDzUiJVPh1KwaZflhagNZ2N2/O7J+f7v5K4xr44vIUjTmx
9sCKgq7kYnpGyaQX2nXtS4Dua+6hZmdN/POHXhYGwmU6WKLkq/W8s
V7Xk3afYQnY4IrkN/6UGKQt0mYBMkNSDPTD1OayU9ha6q1Qoc87En
zZB6Wr1KPJYfrqEUnhFtUauUS649P3FbCTZ7YUQ51ve035l4ILP0s
Rx+YER44l/pU/+jK/FMZQeTu5Q4CCg9qxFD9lLwizNcGgXGtlgY8f
J2CDEe3BPMfBlAVYqMUZq3BrYKiX+mdJ+yE2sSfv9SzoDH6Q=
        passphrase: 87878847
        #host: ${{ secrets.HOST }}
        #username: ${{ secrets.USER }}
        #key: ${{ secrets.SSH_KEY }}
        #passphrase: ${{ secrets.PASSPHRASE }} # Если ваш ssh-ключ защищён фразой-паролем
        script: |
          # Выполняет pull образа с DockerHub
          sudo docker pull hazardbdv/infra_actions
          #остановка всех контейнеров
          sudo docker stop $(sudo docker ps -a -q)
          sudo docker run --rm -d -p 5000:5000 hazardbdv/infra_actions
